clear:
	rm -rf ./node-modules
	rm *.json

install:
	npm init -y
	npm install dotenv --save
	npm install express cors pg sql-template-strings
	npm install @babel/preset-env @babel/core @babel/node nodemon --save-dev
	